batch_size: 32
ckpt_path: checkpoints/vgg16_birds_pretrained_True_Vanilla_sgd_lr0.001_features.28/last.ckpt
data_path: /CUB_200_2011
dataset_name: birds
device: cuda
lamb: 0.0
layer_name: features.28
loss: cross_entropy
lr: 0.001
method: Vanilla
model_name: vgg16
num_epochs: 100
optimizer: sgd
pretrained: true
wandb_api_key: ''
wandb_project_name: ''
