batch_size: 32
ckpt_path: ''
data_path: /ImageNet
dataset_name: imagenet
device: cuda
lamb: 0.0
layer_name: features.28
loss: cross_entropy
lr: 1
method: Vanilla
model_name: vgg16
num_epochs: 15
optimizer: sgd
wandb_api_key: ''
wandb_project_name: ''
