batch_size: 512
ckpt_path: checkpoints/resnet18_cifar10_pretrained_True_Vanilla_sgd_lr0.01_last_conv/last.ckpt
data_path: /cifar10
dataset_name: cifar10
device: cuda
lamb: 0.0
layer_name: last_conv
loss: cross_entropy
lr: 0.01
method: Vanilla
model_name: resnet18
num_epochs: 100
optimizer: sgd
pretrained: true
wandb_api_key: ''
wandb_project_name: ''
